apiVersion: v1
kind: Secret
metadata:
  name: bt-java-apikey-secret
type: Opaque
stringData:
  BEYONDTRUST_API_KEY: "PS-Auth key=<API_KEY>; runas=<RUNAS_USER>;"
  BEYONDTRUST_RUNAS_USER: "<RUNAS_USER>"
  BEYONDTRUST_CERTIFICATE_CONTENT: |
    -----BEGIN CERTIFICATE-----
    <REPLACE_WITH_PEM_CONTENT>
    -----END CERTIFICATE-----
