apiVersion: v1
kind: ConfigMap
metadata:
  name: bt-java-oauth-config
data:
  BEYONDTRUST_ENABLED: "true"
  BEYONDTRUST_API_URL: "https://pam.example.com/BeyondTrust/api/public/v3"
  BEYONDTRUST_USE_APP_USER: "true"
  BEYONDTRUST_IGNORE_SSL_ERRORS: "false"
  BEYONDTRUST_REFRESH_INTERVAL: "300"
  BEYONDTRUST_MANAGED_ACCOUNTS: "LinuxProd.root;WindowsProd.administrator"
  BEYONDTRUST_ALL_MANAGED_ACCOUNTS_ENABLED: "false"
  BEYONDTRUST_SECRET_SAFE_PATHS: "Team/Db,Team/Api"
  BEYONDTRUST_ALL_SECRETS_ENABLED: "false"
  BT_EXAMPLE_ACCOUNT: "bt.acc.LinuxProd.root"
  BT_EXAMPLE_SAFE_PASSWORD: "bt.safe.Team/Db.AppDb.password"
  BT_EXAMPLE_SAFE_USERNAME: "bt.safe.Team/Db.AppDb.username"
