apiVersion: v1
kind: Secret
metadata:
  name: bt-java-oauth-secret
type: Opaque
stringData:
  BEYONDTRUST_CLIENT_ID: "<CLIENT_ID>"
  BEYONDTRUST_CLIENT_SECRET: "<CLIENT_SECRET>"
  BEYONDTRUST_CERTIFICATE_CONTENT: |
    -----BEGIN CERTIFICATE-----
    <REPLACE_WITH_PEM_CONTENT>
    -----END CERTIFICATE-----
