apiVersion: apps/v1
kind: Deployment
metadata:
  name: bt-dotnet-demo-cache-apikey
  namespace: bt-turkcell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bt-dotnet-demo-cache-apikey
  template:
    metadata:
      labels:
        app: bt-dotnet-demo-cache-apikey
    spec:
      containers:
        - name: bt-dotnet-demo-cache-apikey
          image: docker.io/enespekdas/btdotnet-lib:v1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: bt-dotnet-demo-cache-apikey-secret
