kind: ConfigMap
apiVersion: v1
metadata:
  name: beyondtrust-config
  namespace: beyondtrust
immutable: false
data:
  APIKEY: 0a268bec5cd323a52a0a1ed...
  APPLIANCE_NAME_OR_URL: '44.207.168.98:443'
  SCACHESERVER: '0.0.0.0:8443'
  SCACHEUSER: demo_apiuser
  SCACHESERVERCERT: |
    -----BEGIN CERTIFICATE-----
    MIIDHzCCAgegAwIBAgIUHhkTRzcKA6ida3yrwVQD2JvwOtUwDQYJKoZIhvcNAQEL
    BQAwHjEcMBoGA1UEAwwTKi5zdmMuY2x1c3Rlci5sb2NhbDAgFw0yNTA4MjExMzMy
    MzZaGA8yMDc1MDgwOTEzMzIzNlowHjEcMBoGA1UEAwwTKi5zdmMuY2x1c3Rlci5s
    b2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMf61B5LCq+ReVhs
    CUWmeyOqvfT6eooK3oj13BZ6ycv2P6GXO5FguSHeBIdt9xpu+yQ3XcabRZsQ3tTC
    NCPyFmYeub3La/msnGjHbxUvk3m6kI+gHCZxuBVvEp1UMcJWrqWoR7LeCMtHoIC0
    bWN275dO6ISr2fUm3R4CPQuAhnBMsBizzkSK47K79IilJzSteaVasP/o52rJ3keP
    LY0+KAciDDPXeABrN/gFW0qISKKdFGIMvi0Fv1ifMFDkoakseGv6iWWC5x2zui7X
    0LQ/Eb223mWM/BGD69GHir9smz6yAEe7kU1Dz0wACuLhpsdL5EWEVpdyxy9JICE8
    r4hozPkCAwEAAaNTMFEwHQYDVR0OBBYEFL8Z/5aTjkv1MXCS3WYyWUIaWwM4MB8G
    A1UdIwQYMBaAFL8Z/5aTjkv1MXCS3WYyWUIaWwM4MA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAFOATMF05ZQG2asSIdtz/qY56nGMmQOeC1ApbWHh
    K5hIHF/DPNGP6xE7RtEA+R2vb31WTqUvGrek5FDbwyJJRWvtwc+KrcrScFC08tgn
    dckXdxTldQO0uo0UIyUvugq0UbIohV1uRxs4bRneAtzpvk+Tu+Lp2AKalmDuXyDS
    IIMkjWPqi6hFyJbzT+a+yqQl5tC57IxsSpT+bZiQP8iiikfc+VUOabXfrqMF1mSs
    2HUSbQHJ4qdUTn7YyHl1U6aeCk9Rpua7T1hErISO3utmk+/mrRET1vscHKVkQlHD
    UEg+eY4IwrDuEuOQUh7jlbJwQ1XiNISRJFP0dV+7szdEI1E=
    -----END CERTIFICATE-----
  SCACHESERVERCERTKEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDH+tQeSwqvkXlY
    bAlFpnsjqr30+nqKCt6I9dwWesnL9j+hlzuRYLkh3gSHbfcabvskN13Gm0WbEN7U
    wjQj8hZmHrm9y2v5rJxox28VL5N5upCPoBwmcbgVbxKdVDHCVq6lqEey3gjLR6CA
    tG1jdu+XTuiEq9n1Jt0eAj0LgIZwTLAYs85EiuOyu/SIpSc0rXmlWrD/6Odqyd5H
    jy2NPigHIgwz13gAazf4BVtKiEiinRRiDL4tBb9YnzBQ5KGpLHhr+ollgucds7ou
    19C0PxG9tt5ljPwRg+vRh4q/bJs+sgBHu5FNQ89MAAri4abHS+RFhFaXcscvSSAh
    PK+IaMz5AgMBAAECggEAD5R38dOTMGIgi+Yq2MLOJYANZD3JeIy9O/q6Rq69SbHU
    e5s5LavVReayqqHDa8tJWfp4SLCwfRK/kYrUc20jwplSi49YHlpiJdBNKV+MrqH9
    gOW5RmN7XdbKoqLnF4bCUi9TRVkCuAz2BmDy2W9wM3UXLL2Tca6Gm+pnusgsxn3c
    9GxWAZACMPwozUSmlPS0szvJdwIZDhONksIKh0/EvL4xV2rsQ3ZIZ7+FMEmEsLqd
    UeSE7/f5OlOrnz0acglNk8GHeXmZ2xh1EC0T717XropKU6yEtTOGGL5wJOOZynnM
    k1nrTudwVOZKmwaskaABEn/CiVWWcqqmphwb1+ekQwKBgQDOqCs5ydKB+3AiV7Ul
    iMb1R7/gfUZMlxGaDv7C7+8xiLtg2iI47dieEsgMFh5JTm4YEddgj4jtR1QiFbhK
    RTixlhGxgzjdynuGHIRBx5uK2/JHjNNl38ddCWKDLpzCGijJW0H7g6Ns7HLXIKTw
    6y3pEdh/qDv756s0aqAGzEo3gwKBgQD3uoYReNKVSthhA9TuR3dtR6C++NWGnujx
    lchy5zKy6h6IPUqIob/1UmdSCfPwQhOXN3CL1/y7OP/zSUA6lku5AtQZcKvKVSah
    U1dFdyITDPSajwMWcCoUR4ugmylg7ER4xf5lBRQiaaX6k4kd910layISww1j8H7x
    u84bSvUE0wKBgC9vVHSwSbyCPWv0m+Tgr2JvtLBPsQo1htnI5VtTfaDuFKyXhVFx
    7s3h279CeHM1KHon5jsI11I3lC06tRF/MBM7MhZ/21a1eoL/GrCKo75M3CDmR0PU
    CMvnMpCP63V2UbReWRflUGbZI0cT/Cg8o04jRYGP2SzqMVcXvmGxFLwHAoGBANL0
    +vBsBF/v8Z2EBtK290OPKJsYCbVvI41+8Miwi2MCred00kDSBUai2qtpIFtr2YT/
    SA8+adEBdCy4J0L89BTkDLxxT0mpA5GECCB2mATDFpV7zbRQ5fSJDKVDHJSV/qUe
    bkmWbpPzhc2Bz9U97gtMVSLHCWMezOuL87MYPNjTAoGADTx5u3r6QqyiTIQ5FIsy
    w+RTVWnU3sm9hGDCmkLOGg6QOOn4oGks5TS9flP+J+a5BDjJaps3TWTbe8VZoS1V
    RPQehjx8u+ltd0OwELhrHKft0TCasS79l/LB7qJWyids7NIX0em4AEMEi6lYSVxi
    MpbYwDNgyc16Xm3JlGonGWA=
    -----END PRIVATE KEY-----