kind: ConfigMap
apiVersion: v1
metadata:
  name: beyondtrust-config
  namespace: bt-turkcell
immutable: false
data:
  APIKEY: 548b2065c708e40a08cd190e1517c81072bfad7435227b1db40244af368aad97a320d27c6616050d1dbdecf1b60bc366254c480b2ef4dd0f1e4a66df4fefb413
  APPLIANCE_NAME_OR_URL: "pam.quasys.com.tr:443"
  PASSWORDSAFEVERIFY: ""
  PASSWORDSAFECACERT: ""
  SCACHESERVER: "0.0.0.0:8443"
  SCACHEUSER: enes
  SCACHESERVERCERT: |
    -----BEGIN CERTIFICATE-----
    MIID9jCCAt6gAwIBAgIULhVcmwid/0OyCBLCWzSWbJ/RuiEwDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVFIxETAPBgNVBAgMCElzdGFuYnVsMREwDwYDVQQHDAhJ
    c3RhbmJ1bDEWMBQGA1UECgwNc2VjcmV0cy1jYWNoZTERMA8GA1UECwwIcGxhdGZv
    cm0xHjAcBgNVBAMMFXNlY3JldHMtY2FjaGUtc2VydmljZTAeFw0yNjAxMjYxNjI1
    NDRaFw0yODA0MzAxNjI1NDRaMH4xCzAJBgNVBAYTAlRSMREwDwYDVQQIDAhJc3Rh
    bmJ1bDERMA8GA1UEBwwISXN0YW5idWwxFjAUBgNVBAoMDXNlY3JldHMtY2FjaGUx
    ETAPBgNVBAsMCHBsYXRmb3JtMR4wHAYDVQQDDBVzZWNyZXRzLWNhY2hlLXNlcnZp
    Y2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCyOJt+y4aacrxy4yiC
    pi5GRxk4gOazpv5rWZuZp5XiYx6YgmipOtCXu1gfezx4Lox0NZvv5XVux02u9dc3
    qFgRpaJf6iMO+lS0l0AwamEQppGJjQNp9LKJUASdizxhf9TYqcgOO1/hWtYeuL1i
    Fm4vxG3ZTy8xB7hBqGIhYJXH7yTc53B8dC1R+k1MArRe9WAad6aF1WQm0u+e2s7G
    25rPgTol+cRxHLfeD6RyGSlrBCLIOP5XJB469j/rVWYCSZCwdcd+l7zsn3ijC5ds
    bLPdDMGHbnsPnbNVsfwfk6TU1aujzmOGTqo7DgvktbLL7mBqumvBbhWblu8unx90
    aa9pAgMBAAGjbDBqMEkGA1UdEQRCMECCFXNlY3JldHMtY2FjaGUtc2VydmljZYIn
    c2VjcmV0cy1jYWNoZS1zZXJ2aWNlLnN2Yy5jbHVzdGVyLmxvY2FsMB0GA1UdDgQW
    BBQF1XKgQdswbTDYsKnwfcwCpcA9+zANBgkqhkiG9w0BAQsFAAOCAQEAisixqaul
    bKOD+xX5Xw/6JnpAW7yvIl5WnOXDY4aFRz/wSHNyrBmmq7nuGwh4PrjigoYeq/t0
    v3SY9yRhLti9KYcopiWc5uHmp2NahzUq9UYJYG5f7lpuOqtzihyf+blW6jeaPvv3
    tC/L7tETXSjXr8yZpcHbHBn5wilZjD4Cxq0Mzlt9Pp1X7ldc4iEkoMWXiJAzi7H8
    hSxAPwoO9M/85zUsBGQbhkhJo6ll8SQPjnVN/TH+KQ//aIuERORiEgp+vFrYN9b9
    5Ia3uUVaRAjP8feN6JNbnS4mMpwl/6QZzFim+imU19EmdMsIRpUgblR6NStmNsqw
    icqfwZqJYAqU5w==
    -----END CERTIFICATE-----
  SCACHESERVERCERTKEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyOJt+y4aacrxy
    4yiCpi5GRxk4gOazpv5rWZuZp5XiYx6YgmipOtCXu1gfezx4Lox0NZvv5XVux02u
    9dc3qFgRpaJf6iMO+lS0l0AwamEQppGJjQNp9LKJUASdizxhf9TYqcgOO1/hWtYe
    uL1iFm4vxG3ZTy8xB7hBqGIhYJXH7yTc53B8dC1R+k1MArRe9WAad6aF1WQm0u+e
    2s7G25rPgTol+cRxHLfeD6RyGSlrBCLIOP5XJB469j/rVWYCSZCwdcd+l7zsn3ij
    C5dsbLPdDMGHbnsPnbNVsfwfk6TU1aujzmOGTqo7DgvktbLL7mBqumvBbhWblu8u
    nx90aa9pAgMBAAECggEAEh/FGmwmtGK6LOHSfxTYzF9THoanT3pKUc7zTrk2+iaT
    2DUc4SbgyylrcQomkF9Fe9Tu1oLqghlFGmeYWynkyOij/maQaafGAPaHudS7qcaS
    st8TC42tsV6glYfxHEY0dlMvy9i4a7HB6C5n3geDbZqnhCu0FCOhlpXB4vyQRtxs
    yV4UjSSRG3i3Bt0mg+PWyzNqxhBkOZqn06sWjkzUuy8MoG4u0VaE9q5Phlp1iTwS
    jjDaq6zIbVZhww+dP49f8jHmFGOzVnDj2v/q7WZCd47I1fInAqNQBBkQ+eiEm6uK
    FcHi4GSMNUeno4YnKs65rcmHWiLTbAYqgCA8Ti/ePQKBgQDJWgvi3nc1fUOuctRI
    7xHmqvaDLrX119BUV6SA9xvJCWFykTlboiYxrvzrhgTQXrT1a/1UisZkrnL2pwWV
    NCtX4Dj+H7YeQd/IxKkfnJj0P4lhFgSmo5/lj9veZwu++SUl4zqflf+jOSRp4L3r
    9fAsxsxoVmPJrvWgiC5SyUdypQKBgQDil3EDgG0jT4yR8HEnZmMvG9FhM7h84E32
    SlEsaGYtLCSH2StCZ/0+fdf5b9R5epBjU8k9+jYjZ7QEMkXf3/IWYBBfddcia8jJ
    4wWaPqevwi+imOGWZWQ7BGoXf8xHTLy3wIVMaXqv766n5Sao3gF8g+WE56/TpVrj
    pR2wstkCdQKBgA0SopjtNrIrWtyVqgC+PNxMF0s3GitHAsinFBAnew9XY5NLqHyx
    j2dEZDlqbx+UNo2EoGL/y5e319D50Rv50iKXdTvSlUFrp3rigdSCl0+sXGAITO8A
    yp3d9DmBWTrh9C58jU7VL07Ko/mX1NzgD+LoWVcg3MO4b0wn61IGrXPdAoGBANnk
    gVO5srlq7KUGDvmxVp1dZbnQD49d7vpwuqA2gFLeCP7tkdDYyMjIIOCHbk2m06QA
    VRuZOWhQd+Y1JcZDxrtHg1cYrVk3Rq0E90U9DOlRlZcI5p1GQN0TwKV6Skkh/LPC
    mSxCni0DEfP3wnZOjiVbfGGSnhyq/Ly98dASG+ZlAoGBAI6paryChrTIlB2RJAXQ
    7LDOVilo+xZKqRBXNcbzvTD5aQhTq6ZbH6hYP2byQsdBYtnfUBTCyXcViilqAcgd
    gDVxd3pNJEsznqqARzfWx6YGuqYmo23JZfCV4xzEDTfmzJ28jYinkImZjRoOHcW4
    5G6AdUBdare2J1qEejJEDGCz
    -----END PRIVATE KEY-----
